export var catalogItems = [
  {
    id: 23,
    title: "I Dream in Another Language",
    rating: 7.9,
    category: "Movie",
    views: 1392,
    status: "Visible",
    createdDate: "24 Oct 2021",
  },
  {
    id: 24,
    title: "Benched",
    rating: 7.1,
    category: "Movie",
    views: 1093,
    status: "Hidden",
    createdDate: "24 Oct 2021",
  },
  {
    id: 25,
    title: "Whitney",
    rating: 6.3,
    category: "TV Show",
    views: 723,
    status: "Visible",
    createdDate: "24 Oct 2021",
  },
  {
    id: 26,
    title: "Blindspotting",
    rating: 8.4,
    category: "TV Show",
    views: 2457,
    status: "Visible",
    createdDate: "24 Oct 2021",
  },
  {
    id: 27,
    title: "I Dream in Another Language",
    rating: 7.9,
    category: "Movie",
    views: 1392,
    status: "Visible",
    createdDate: "24 Oct 2021",
  },
  {
    id: 28,
    title: "Benched",
    rating: 7.1,
    category: "TV Show",
    views: 1093,
    status: "Hidden",
    createdDate: "24 Oct 2021",
  },
  {
    id: 29,
    title: "Whitney",
    rating: 6.3,
    category: "Cartoon",
    views: 723,
    status: "Visible",
    createdDate: "24 Oct 2021",
  },
  {
    id: 30,
    title: "Blindspotting",
    rating: 8.4,
    category: "Movie",
    views: 2457,
    status: "Visible",
    createdDate: "24 Oct 2021",
  },
  {
    id: 31,
    title: "I Dream in Another Language",
    rating: 7.9,
    category: "Movie",
    views: 1392,
    status: "Visible",
    createdDate: "24 Oct 2021",
  },
  {
    id: 32,
    title: "Benched",
    rating: 7.1,
    category: "Movie",
    views: 1093,
    status: "Hidden",
    createdDate: "24 Oct 2021",
  },
];

export var userItems = [
  {
    id: 23,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Premium",
    comments: 13,
    reviews: 1,
    status: "Approved",
    createdDate: "24 Oct 2021",
  },
  {
    id: 24,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Free",
    comments: 1,
    reviews: 15,
    status: "Approved",
    createdDate: "24 Oct 2021",
  },
  {
    id: 25,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Premium",
    comments: 6,
    reviews: 6,
    status: "Approved",
    createdDate: "24 Oct 2021",
  },
  {
    id: 26,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Free",
    comments: 11,
    reviews: 15,
    status: "Banned",
    createdDate: "24 Oct 2021",
  },
  {
    id: 27,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Basic",
    comments: 0,
    reviews: 0,
    status: "Approved",
    createdDate: "24 Oct 2021",
  },
  {
    id: 28,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Free",
    comments: 2,
    reviews: 1,
    status: "Approved",
    createdDate: "24 Oct 2021",
  },
  {
    id: 29,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Cinematic",
    comments: 65,
    reviews: 0,
    status: "Approved",
    createdDate: "24 Oct 2021",
  },
  {
    id: 30,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Premium",
    comments: 0,
    reviews: 0,
    status: "Banned",
    createdDate: "24 Oct 2021",
  },
  {
    id: 31,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Premium",
    comments: 13,
    reviews: 1,
    status: "Approved",
    createdDate: "24 Oct 2021",
  },
  {
    id: 32,
    name: "John Doe",
    email: "email@email.com",
    username: "Username",
    pricingPlan: "Free",
    comments: 1,
    reviews: 15,
    status: "Banned",
    createdDate: "24 Oct 2021",
  },
];

export var comments = [
  {
    id: 23,
    item: "I Dream in Another Language",
    author: "Brian Cranston",
    text: "Lorem Ipsum is simply dummy text...",
    rating: 7.9,
    like_dislike: "12 / 7",
    createdDate: "24 Oct 2021",
  },
  {
    id: 24,
    item: "Benched",
    author: "John Doe",
    text: "Lorem Ipsum is simply dummy text...",
    rating: 8.6,
    like_dislike: "67 / 22",
    createdDate: "24 Oct 2021",
  },
  {
    id: 25,
    item: "Whitney",
    author: "Jesse Plemons",
    rating: 8.0,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "44 / 5",
    createdDate: "24 Oct 2021",
  },
  {
    id: 26,
    item: "Blindspotting",
    author: "Matt Jones",
    rating: 9.1,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "20 / 6",
    createdDate: "24 Oct 2021",
  },
  {
    id: 27,
    item: "I Dream in Another Language",
    author: "Tess Harper",
    rating: 8.5,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "8 / 132",
    createdDate: "24 Oct 2021",
  },
  {
    id: 28,
    item: "Benched",
    author: "John Doe",
    rating: 7.0,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "6 / 1",
    createdDate: "24 Oct 2021",
  },
  {
    id: 29,
    item: "Whitney",
    author: "Jesse Plemons",
    rating: 9.0,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "10 / 0",
    createdDate: "24 Oct 2021",
  },
  {
    id: 30,
    item: "Blindspotting",
    author: "Jonathan Banks",
    rating: 6.2,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "13 / 14",
    createdDate: "24 Oct 2021",
  },
  {
    id: 31,
    item: "I Dream in Another Language",
    author: "John Doe",
    rating: 7.9,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "12 / 7",
    createdDate: "24 Oct 2021",
  },
  {
    id: 32,
    item: "Benched",
    author: "Brian Cranston",
    rating: 8.6,
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "67 / 22",
    createdDate: "24 Oct 2021",
  },
];

export var reviews = [
  {
    id: 23,
    item: "I Dream in Another Language",
    author: "Jesse Plemons",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "12 / 7",
    createdDate: "24 Oct 2021",
  },
  {
    id: 24,
    item: "Benched",
    author: "Matt Jones",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "67 / 22",
    createdDate: "24 Oct 2021",
  },
  {
    id: 25,
    item: "Whitney",
    author: "Tess Harper",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "44 / 5",
    createdDate: "24 Oct 2021",
  },
  {
    id: 26,
    item: "Blindspotting",
    author: "John Doe",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "20 / 6",
    createdDate: "24 Oct 2021",
  },
  {
    id: 27,
    item: "I Dream in Another Language",
    author: "Jonathan Banks",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "8 / 132",
    createdDate: "24 Oct 2021",
  },
  {
    id: 28,
    item: "Benched",
    author: "John Doe",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "6 / 1",
    createdDate: "24 Oct 2021",
  },
  {
    id: 29,
    item: "Whitney",
    author: "Jesse Plemons",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "10 / 0",
    createdDate: "24 Oct 2021",
  },
  {
    id: 30,
    item: "Blindspotting",
    author: "John Doe",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "13 / 14",
    createdDate: "24 Oct 2021",
  },
  {
    id: 31,
    item: "I Dream in Another Language",
    author: "Brian Cranston",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "12 / 7",
    createdDate: "24 Oct 2021",
  },
  {
    id: 32,
    item: "Benched",
    author: "Jonathan Banks",
    text: "Lorem Ipsum is simply dummy text...",
    like_dislike: "67 / 22",
    createdDate: "24 Oct 2021",
  },
];
